name: Tests on Rocky Linux 9

# Trigger the workflow on push or pull request
on: [push, pull_request]

jobs:
  distribution-check:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:9
    steps:
    - uses: actions/checkout@v1
    - name: Are we really on Rocky Linux?
      run: |
        cat /etc/os-release